### ISSUE TITLE
load original video error when running

### ISSUE THREAD

**Issue by choodooyun** [Donato-touch/touch-of-animatediff#1]
![오류1](https://github.com/user-attachments/assets/5f0e440f-6090-49da-b345-e1eda51a78b9)

**Comment by Donato-touch** [comment]
비디오 경로가 잘 들어갔나요? 
video: 에 있는 경로에 영상 파일이 없는지 확인해주세요

**Comment by choodooyun** [comment]
네~ 영상 보면서 example-resource 들어가서 비디오 경로 복사해서 넣었습니다. 근데도 계속 이러는 이유를 모르겠네요...ㅜㅜ

**Comment by choodooyun** [comment]
> 비디오 경로가 잘 들어갔나요? video: 에 있는 경로에 영상 파일이 없는지 확인해주세요

네~ 영상 보면서 example-resource 들어가서 비디오 경로 복사해서 넣었습니다. 근데도 계속 이러는 이유를 모르겠네요... ㅜㅜ
![오류6](https://github.com/user-attachments/assets/5bd695e8-d0de-42be-87e5-829e3eca51c8)

**Comment by Donato-touch** [comment]
영상 경로에는 `.... \cdy\comfy\example\resource\test_dance.mp4` 까지 다 넣어야 합니다

**Comment by choodooyun** [comment]
> 영상 경로에는 까지 다 넣어야 합니다`.... \cdy\comfy\example\resource\test_dance.mp4

아... 그런가요? 뒤에 test_dance.mp4는 수동으로 추가로 적어야 하나요?

**Comment by choodooyun** [comment]
> > 영상 경로에는 까지 다 넣어야 합니다'.... \cdy\comfy\example\resource\test_dance.mp4
> 
> 아... 그런가요? 뒤에 test_dance.mp4는 수동으로 추가로 적어야 하나요?

아... 됐습니다..ㅜㅜ  정말 감사합니다~ ㅎㅎ  뒤에 D:\abc\cdy\comfy\example\resource\test_dance.mp4 이렇게 붙이니 되네요..ㅜㅜ

**Comment by choodooyun** [comment]
> 영상 경로에는 까지 다 넣어야 합니다`.... \cdy\comfy\example\resource\test_dance.mp4`

아고... 마지막에서 이런게 뜨는데.. 뭔지 알수 있을까요? ㅜㅜ comfyui 오류는 아닌거 같은데... 
![오류9](https://github.com/user-attachments/assets/b7a31ef8-5430-4e5b-9dd2-1b6cbc93c4fe)
![오류8](https://github.com/user-attachments/assets/b3e7a130-1101-46e7-8a7a-5b769d5bc840)

**Comment by Donato-touch** [comment]
이건 메모리가 부족한거네요 아마 RAM쪽일겁니다

**Comment by choodooyun** [comment]
> 이건 메모리가 부족한거네요 아마 RAM쪽일겁니다

네~ 컴 업글 좀 해야겠네요..ㅜ   감사합니다~^^
